hotfix : need to align content type returned by API and documented,
penapi_client.exceptions.ApiValueError: Invalid content_type returned. Content_type='application/json;charset=UTF-8' was returned when only {'application/json'} are defined for status_code=200